import { useCallback, useEffect, useRef, type Dispatch, type SetStateAction } from "react";
import {
  buildReportSourceInput,
} from "@/features/studio/module-runtime-input";
import {
  createGenerationSignature,
  createGeneratedDraftAsset,
  detectImplicitLongFormClarification,
  inferRequestedHtmlPageCount,
  resolveGenerationIntent,
  streamGenerateHtmlReport,
  type PageFitMeasurement,
  type StudioGenerateStreamEvent,
} from "@/features/studio/generation";
import type {
  GeneratedDraftAsset,
  LongFormClarificationResolution,
  TemplateId,
  WorkbenchModuleUsageMode,
  WorkbenchProject,
} from "@/features/studio/types";
import { createIntakeThread } from "../runtime-intake";
import type { StreamUiState } from "../runtime-shell-contract";
import type { Message } from "../runtime-types";
import {
  useStudioBriefState,
  useStudioProjectActions,
  useWorkbenchStudioStore,
} from "../studio/store";

type UseStudioGenerationFlowArgs = {
  project: WorkbenchProject | null;
  streamUi: StreamUiState;
  isDeckReviewLocked: boolean;
  intakeMessages: Message[];
  generatedHtmlReport: GeneratedDraftAsset["htmlReport"] | null;
  longFormClarification: WorkbenchProject["longFormClarification"];
  shellBootState: ReturnType<typeof useWorkbenchStudioStore.getState>["shell"]["bootState"];
  handleStreamEvent: (event: StudioGenerateStreamEvent) => void;
  resetStreamUi: () => void;
  setStreamUi: Dispatch<SetStateAction<StreamUiState>>;
  appendStreamTranscript: (text: string) => void;
  onConversationQueued?: () => void;
  queueDeckReview: (
    briefSource: string,
    report: NonNullable<GeneratedDraftAsset["htmlReport"]>,
    repairPass?: number,
    options?: {
      seededMeasurements?: Record<number, PageFitMeasurement>;
      pendingPages?: number[];
      startedAt?: number | null;
      mode?: "auto" | "manual";
      markAutoOptimized?: boolean;
    },
  ) => void;
};

export function useStudioGenerationFlow(args: UseStudioGenerationFlowArgs) {
  const {
    project,
    streamUi,
    isDeckReviewLocked,
    intakeMessages,
    generatedHtmlReport,
    longFormClarification,
    shellBootState,
    handleStreamEvent,
    resetStreamUi,
    setStreamUi,
    appendStreamTranscript,
    onConversationQueued,
    queueDeckReview,
  } = args;

  const streamAbortControllerRef = useRef<AbortController | null>(null);
  const autoGeneratedProjectIdRef = useRef<string | null>(null);

  const brief = useStudioBriefState();
  const {
    replaceCurrentProject,
    setStatusLine,
    setBriefMessages,
    setIntakeInput,
    setBuildingStoryline,
    setGeneratingReport,
    commitGeneration,
  } = useStudioProjectActions();

  const replaceLongFormClarification = useCallback((nextState: WorkbenchProject["longFormClarification"]) => {
    if (!project) {
      return;
    }

    replaceCurrentProject(
      {
        ...project,
        longFormClarification: nextState,
        updatedAt: new Date().toISOString(),
      },
      {
        history: false,
        mode: "editor",
      },
    );
  }, [project, replaceCurrentProject]);

  const runHtmlGeneration = useCallback(async (
    briefSource: string,
    overrideIntent?: {
      generationMode?: WorkbenchProject["generationMode"];
      moduleUsageMode?: WorkbenchProject["moduleUsageMode"];
      requestedPageCount?: WorkbenchProject["requestedPageCount"];
      suppressInferredPageCount?: boolean;
    },
  ) => {
    streamAbortControllerRef.current?.abort();
    const abortController = new AbortController();
    streamAbortControllerRef.current = abortController;
    const latestExplicitPageCount = inferRequestedHtmlPageCount(briefSource);
    const shouldSuppressKeptStandardInference =
      !overrideIntent?.suppressInferredPageCount &&
      longFormClarification.status === "resolved" &&
      longFormClarification.trigger === "explicit-8-9-pages" &&
      longFormClarification.resolution === "keep-standard" &&
      !(
        Number.isInteger(latestExplicitPageCount) &&
        (latestExplicitPageCount ?? 0) >= 10
      );
    const generationIntent = resolveGenerationIntent(briefSource, {
      generationMode: overrideIntent?.generationMode ?? project?.generationMode ?? "standard",
      moduleUsageMode: overrideIntent?.moduleUsageMode ?? project?.moduleUsageMode ?? "disabled",
      requestedPageCount:
        overrideIntent?.requestedPageCount ?? project?.requestedPageCount ?? null,
      suppressInferredPageCount:
        overrideIntent?.suppressInferredPageCount ?? shouldSuppressKeptStandardInference,
    });

    try {
      const result = await streamGenerateHtmlReport(briefSource, brief.aiSettings, {
        signal: abortController.signal,
        onEvent: handleStreamEvent,
        intent: generationIntent,
      });

      if (abortController.signal.aborted) {
        return;
      }

      if (result.provider !== "model" || !result.htmlReport) {
        setStatusLine(
          result.reason || "Codex could not generate the HTML report this time.",
        );
        setStreamUi((current) => ({
          ...current,
          isStreaming: false,
          error: result.reason ?? "Codex could not generate the HTML report this time.",
          stage: "Generation failed",
        }));
        return;
      }

      const asset = createGeneratedDraftAsset({
        draft: result.draft,
        signature: createGenerationSignature(
          briefSource,
          result.pages,
          (project?.templateId ?? "blank") as TemplateId,
        ),
        templateId: (project?.templateId ?? "blank") as TemplateId,
        provider: result.provider,
        mode: "content",
        model: result.model,
        htmlReport: result.htmlReport,
      });

      commitGeneration(
        {
          projectName: result.htmlReport.title,
          sourceText: briefSource,
          generationMode: generationIntent.generationMode,
          moduleUsageMode: generationIntent.moduleUsageMode,
          requestedPageCount: generationIntent.requestedPageCount,
          pages: result.pages,
          generatedDraft: asset,
          workflowStage: "generated",
        },
        `Codex generated a ${result.htmlReport.pageCount}-page HTML report directly in the Studio.`,
      );
      queueDeckReview(briefSource, result.htmlReport, 0, {
        mode: "auto",
        markAutoOptimized: true,
      });
      resetStreamUi();
    } catch (error) {
      if (abortController.signal.aborted) {
        setStatusLine("Studio generation canceled.");
        return;
      }

      const reason =
        error instanceof Error ? error.message : "Studio generation failed.";
      setStatusLine(reason);
      setStreamUi((current) => ({
        ...current,
        isStreaming: false,
        error: reason,
        stage: "Generation failed",
      }));
      appendStreamTranscript(`[Error]\n${reason}`);
    } finally {
      if (streamAbortControllerRef.current === abortController) {
        streamAbortControllerRef.current = null;
      }
    }
  }, [
    appendStreamTranscript,
    brief.aiSettings,
    commitGeneration,
    handleStreamEvent,
    longFormClarification.resolution,
    longFormClarification.status,
    longFormClarification.trigger,
    project?.generationMode,
    project?.moduleUsageMode,
    project?.requestedPageCount,
    project?.templateId,
    queueDeckReview,
    resetStreamUi,
    setStreamUi,
    setStatusLine,
  ]);

  const cancelStreamingGeneration = useCallback(() => {
    streamAbortControllerRef.current?.abort();
    streamAbortControllerRef.current = null;
    setGeneratingReport(false);
    setBuildingStoryline(false);
    setStatusLine("Studio generation canceled.");
    setStreamUi((current) => ({
      ...current,
      isStreaming: false,
      error: current.error ?? "Generation canceled.",
      stage: "Generation canceled",
    }));
  }, [setBuildingStoryline, setGeneratingReport, setStatusLine, setStreamUi]);

  const buildStorylineFromInput = useCallback(async () => {
    if (!project) {
      return;
    }

    if (isDeckReviewLocked) {
      setStatusLine("Studio is still reviewing the latest deck. Wait a moment before regenerating.");
      return;
    }

    const briefSource = buildReportSourceInput({
      briefMessages: intakeMessages,
      pendingInput: brief.intakeInput,
    }).briefText;

    if (!briefSource.trim()) {
      setStatusLine("Give me some report context first, then I can generate the HTML report.");
      return;
    }

    setBuildingStoryline(true);
    setStatusLine("Codex is generating the report now. This can take around 30 to 90 seconds.");
    const pendingInput = brief.intakeInput.trim();
    if (pendingInput) {
      setBriefMessages([...project.briefMessages, { role: "user", text: pendingInput }]);
      setIntakeInput("");
    }

    try {
      await runHtmlGeneration(briefSource);
    } catch (error) {
      setStatusLine(
        error instanceof Error
          ? error.message
          : "Report generation failed before the editor could open.",
      );
    } finally {
      setBuildingStoryline(false);
    }
  }, [
    brief.intakeInput,
    intakeMessages,
    isDeckReviewLocked,
    project,
    runHtmlGeneration,
    setBriefMessages,
    setBuildingStoryline,
    setIntakeInput,
    setStatusLine,
  ]);

  const regenerateReportContent = useCallback(async () => {
    if (!project?.sourceText.trim()) {
      setStatusLine("I still need source material before I can generate the HTML report.");
      return;
    }

    if (isDeckReviewLocked) {
      setStatusLine("Studio is still reviewing the latest deck. Wait a moment before regenerating.");
      return;
    }

    setGeneratingReport(true);
    setStatusLine("Regenerating the HTML report...");
    try {
      await runHtmlGeneration(project.sourceText);
    } catch (error) {
      setStatusLine(
        error instanceof Error ? error.message : "HTML report regeneration failed.",
      );
    } finally {
      setGeneratingReport(false);
    }
  }, [
    isDeckReviewLocked,
    project?.sourceText,
    runHtmlGeneration,
    setGeneratingReport,
    setStatusLine,
  ]);

  const updateProjectModuleUsageMode = useCallback((nextMode: WorkbenchModuleUsageMode) => {
    if (!project || project.moduleUsageMode === nextMode) {
      return;
    }

    replaceCurrentProject(
      {
        ...project,
        moduleUsageMode: nextMode,
        updatedAt: new Date().toISOString(),
      },
      {
        history: {
          scope: "brief",
          label: "Change module usage mode",
          fields: ["moduleUsageMode"],
        },
        mode: "editor",
        statusLine:
          nextMode === "disabled"
            ? "Author modules are off for automatic generation."
            : nextMode === "fallback"
              ? "Stable modules will only be used as fallback."
              : "Only stable chart modules can assist evidence pages.",
      },
    );
  }, [project, replaceCurrentProject]);

  const handleLongFormClarificationChoice = useCallback(async (
    resolution: LongFormClarificationResolution,
  ) => {
    if (!project || !longFormClarification.trigger) {
      return;
    }

    if (brief.isGeneratingReport || streamUi.isStreaming || isDeckReviewLocked) {
      setStatusLine("Wait for the current generation or review pass to finish before changing the deck length.");
      return;
    }

    const nextGenerationMode: WorkbenchProject["generationMode"] =
      resolution === "long-form-10" || resolution === "long-form-12"
        ? "long-form"
        : "standard";
    const nextRequestedPageCount =
      resolution === "long-form-10"
        ? 10
        : resolution === "long-form-12"
          ? 12
          : null;
    const nextProject = {
      ...project,
      generationMode: nextGenerationMode,
      requestedPageCount: nextRequestedPageCount,
      longFormClarification: {
        status: "resolved" as const,
        trigger: longFormClarification.trigger,
        resolution,
      },
      updatedAt: new Date().toISOString(),
    };

    replaceCurrentProject(nextProject, {
      history: false,
      mode: "editor",
      statusLine:
        resolution === "keep-standard"
          ? "Keeping the current conversation concise."
          : `Expanding this conversation into a ${nextRequestedPageCount}-page long-form deck.`,
    });

    const shouldGenerate =
      resolution === "long-form-10" ||
      resolution === "long-form-12" ||
      (resolution === "keep-standard" &&
        longFormClarification.trigger === "explicit-8-9-pages");

    if (!shouldGenerate) {
      return;
    }

    setGeneratingReport(true);
    try {
      await runHtmlGeneration(project.sourceText, {
        generationMode: nextGenerationMode,
        moduleUsageMode: project.moduleUsageMode,
        requestedPageCount: nextRequestedPageCount,
        suppressInferredPageCount:
          resolution === "keep-standard" &&
          longFormClarification.trigger === "explicit-8-9-pages",
      });
    } catch (error) {
      setStatusLine(
        error instanceof Error ? error.message : "Studio could not update the deck length.",
      );
    } finally {
      setGeneratingReport(false);
    }
  }, [
    brief.isGeneratingReport,
    isDeckReviewLocked,
    longFormClarification.trigger,
    project,
    replaceCurrentProject,
    runHtmlGeneration,
    setGeneratingReport,
    setStatusLine,
    streamUi.isStreaming,
  ]);

  const continueConversation = useCallback(async (nextMessage?: string) => {
    if (!project) {
      return;
    }

    if (
      longFormClarification.status === "pending" &&
      longFormClarification.trigger === "explicit-8-9-pages"
    ) {
      setStatusLine("Choose 10 pages, 12 pages, or keep the deck concise before Studio generates the first draft.");
      return;
    }

    if (isDeckReviewLocked) {
      setStatusLine("Studio is still reviewing the latest deck. Wait a moment before asking for another revision.");
      return;
    }

    const trimmedMessage = nextMessage?.trim() ?? "";
    const nextMessages = trimmedMessage
      ? [...project.briefMessages, { role: "user" as const, text: trimmedMessage }]
      : project.briefMessages;
    const briefSource = buildReportSourceInput({
      briefMessages: createIntakeThread(nextMessages),
    }).briefText;

    if (!briefSource.trim()) {
      setStatusLine("Describe the PPT change you need before asking Studio to regenerate.");
      return;
    }

    if (trimmedMessage) {
      replaceCurrentProject(
        {
          ...project,
          briefMessages: nextMessages,
          sourceText: briefSource,
          workflowStage: "intake",
          updatedAt: new Date().toISOString(),
        },
        {
          history: {
            scope: "brief",
            label: "Continue AI conversation",
            fields: ["briefMessages", "sourceText", "workflowStage"],
          },
          statusLine: "Queued your latest edit request.",
          mode: "editor",
        },
      );
      onConversationQueued?.();
    }

    setGeneratingReport(true);
    setStatusLine("Codex is revising the report in the split Studio view.");

    try {
      await runHtmlGeneration(briefSource);
    } catch (error) {
      setStatusLine(
        error instanceof Error ? error.message : "Report generation failed during the AI conversation.",
      );
    } finally {
      setGeneratingReport(false);
    }
  }, [
    isDeckReviewLocked,
    longFormClarification.status,
    longFormClarification.trigger,
    project,
    replaceCurrentProject,
    runHtmlGeneration,
    setGeneratingReport,
    setStatusLine,
    onConversationQueued,
  ]);

  useEffect(() => {
    return () => {
      streamAbortControllerRef.current?.abort();
    };
  }, []);

  useEffect(() => {
    if (
      !project ||
      shellBootState !== "ready" ||
      project.workflowStage !== "intake" ||
      project.generatedDraft?.htmlReport ||
      !project.sourceText.trim() ||
      longFormClarification.status === "pending"
    ) {
      return;
    }

    if (autoGeneratedProjectIdRef.current === project.id) {
      return;
    }

    const timeoutId = window.setTimeout(() => {
      autoGeneratedProjectIdRef.current = project.id;
      void continueConversation();
    }, 120);

    return () => window.clearTimeout(timeoutId);
  }, [
    continueConversation,
    longFormClarification.status,
    project,
    project?.generatedDraft?.htmlReport,
    project?.id,
    project?.sourceText,
    project?.workflowStage,
    shellBootState,
  ]);

  useEffect(() => {
    if (
      !project ||
      !generatedHtmlReport ||
      longFormClarification.status !== "idle"
    ) {
      return;
    }

    const suggestion = detectImplicitLongFormClarification(project.sourceText, {
      generationMode: project.generationMode,
      requestedPageCount: project.requestedPageCount,
    });
    if (suggestion?.trigger !== "long-input-opportunity") {
      return;
    }

    replaceLongFormClarification({
      status: "pending",
      trigger: suggestion.trigger,
      resolution: null,
    });
    setStatusLine("This brief can support a longer deck. I added an expansion option in the conversation.");
  }, [
    generatedHtmlReport,
    longFormClarification.status,
    project,
    project?.generationMode,
    project?.requestedPageCount,
    project?.sourceText,
    replaceLongFormClarification,
    setStatusLine,
  ]);

  return {
    buildStorylineFromInput,
    regenerateReportContent,
    continueConversation,
    cancelStreamingGeneration,
    handleLongFormClarificationChoice,
    updateProjectModuleUsageMode,
  };
}
