import type { ModuleRegistryEntry } from '../types';
import { STRATEGY_MODULE_EXAMPLES } from './constants';

export const MODULE_REGISTRY: ModuleRegistryEntry[] = [
  {
    id: "core.metrics",
    kind: "metrics",
    label: "Metrics",
    category: "evidence",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Headline evidence block for the four numbers that anchor the page.",
    description: "Headline figures, KPI cards, and quantified proof.",
    promptHint: "Use when the page needs reported numbers or hard evidence.",
    useCases: [
      "Summarize the four most important numbers on the page",
      "Anchor a page with quantitative proof before deeper explanation",
    ],
    searchTerms: ["kpi", "numbers", "facts", "headline metric", "evidence"],
    rendererCapabilities: ["metric-grid"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps keep quantitative proof concise and slide-ready.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Keep metric labels concise and executive-readable.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "metrics.headline-proof",
        label: "Headline proof",
        description: "A simple four-number evidence block for a page thesis.",
      },
    ],
    fields: [
      {
        id: "metric-proof",
        label: "Proof points",
        type: "evidence",
        description: "Four concise proof points or KPI-style statements.",
        required: true,
      },
    ],
    order: 10,
    featured: true,
  },
  {
    id: "core.bars",
    kind: "bars",
    label: "Bars",
    category: "comparison",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Comparison block for ranked categories, options, or segments.",
    description: "Ranking, distribution, and side-by-side comparison views.",
    promptHint: "Use when the page needs four comparisons to be immediately obvious.",
    useCases: [
      "Compare leading options, risks, or segments",
      "Show relative magnitude across categories",
    ],
    searchTerms: ["bar", "ranking", "comparison", "distribution", "benchmark"],
    rendererCapabilities: ["bar-comparison"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps comparisons read as concise executive tradeoffs.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Keep comparisons clear and slide-native.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "bars.comparison-proof",
        label: "Comparison proof",
        description: "Compare a short set of options, risks, or segments.",
      },
    ],
    fields: [
      {
        id: "comparison-set",
        label: "Comparison set",
        type: "comparison-axis",
        description: "Four categories or options to compare side by side.",
        required: true,
      },
    ],
    order: 20,
    featured: true,
  },
  {
    id: "core.line",
    kind: "line",
    label: "Line",
    category: "evidence",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Trend block for time-based progression, maturity, or trajectory.",
    description: "Trend lines, maturity paths, and time-based narratives.",
    promptHint: "Use when the page needs progression over time or milestone maturity.",
    useCases: [
      "Show how maturity, adoption, or urgency changes over time",
      "Turn a timeline into a trend-led story",
    ],
    searchTerms: ["trend", "line", "timeline", "maturity", "progression"],
    rendererCapabilities: ["trend-line"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps keep the curve or maturity story concise.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Express time-based progression in clean stage language.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "line.maturity-path",
        label: "Maturity path",
        description: "Use a line to show progression or stage shift over time.",
      },
    ],
    fields: [
      {
        id: "time-path",
        label: "Time path",
        type: "curve",
        description: "A four-point curve, sequence, or maturity path over time.",
        required: true,
      },
    ],
    order: 30,
    featured: true,
  },
  {
    id: "core.matrix",
    kind: "matrix",
    label: "Matrix",
    category: "comparison",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Two-axis block for structured comparison or categorization.",
    description: "Two-axis comparison and structured categorization.",
    promptHint: "Use when the page needs to compare two dimensions or sort ideas into buckets.",
    useCases: [
      "Map opportunities by impact versus complexity",
      "Split categories into near-term and strategic bets",
    ],
    searchTerms: ["matrix", "grid", "quadrant", "two axis", "tradeoff"],
    rendererCapabilities: ["matrix-grid"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps matrix content stay concise and comparable.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Keep matrix cells brief and decision-oriented.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "matrix.two-axis",
        label: "Two-axis comparison",
        description: "Map categories across two decision axes.",
      },
    ],
    fields: [
      {
        id: "x-axis",
        label: "X axis",
        type: "comparison-axis",
        description: "The horizontal comparison axis for the matrix.",
        required: false,
      },
      {
        id: "y-axis",
        label: "Y axis",
        type: "comparison-axis",
        description: "The vertical comparison axis for the matrix.",
        required: false,
      },
    ],
    order: 40,
    featured: true,
  },
  {
    id: "core.flow",
    kind: "flow",
    label: "Flow",
    category: "logic",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Sequential logic block for cause-effect or process explanation.",
    description: "Sequential logic, operating flows, and causal walkthroughs.",
    promptHint: "Use when the page needs a four-step logic chain or process explanation.",
    useCases: [
      "Explain how one condition leads to another",
      "Walk through a process, intervention, or operating path",
    ],
    searchTerms: ["flow", "process", "logic", "sequence", "steps"],
    rendererCapabilities: ["step-flow"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps logic chains read cleanly in sequence.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Keep step chains concise and directional.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "flow.logic-chain",
        label: "Logic chain",
        description: "Explain why one condition leads to the next.",
      },
    ],
    fields: [
      {
        id: "logic-chain",
        label: "Logic chain",
        type: "step",
        description: "Four ordered steps that explain the logic on the page.",
        required: true,
      },
    ],
    order: 50,
    featured: true,
  },
  {
    id: "core.gantt",
    kind: "gantt",
    label: "Gantt",
    category: "roadmap",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Execution roadmap block for workstreams and timing.",
    description: "Roadmaps, workstreams, and time-phased execution plans.",
    promptHint: "Use when the page needs execution timing, dependencies, or rollout sequencing.",
    useCases: [
      "Lay out workstreams by year or quarter",
      "Show the order of rollout and dependency logic",
    ],
    searchTerms: ["gantt", "roadmap", "execution", "timeline", "workstreams"],
    rendererCapabilities: ["timeline-roadmap"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps execution plans stay readable and milestone-led.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Keep workstream labels and milestones concise.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "gantt.execution-roadmap",
        label: "Execution roadmap",
        description: "Lay out workstreams and timing on a single slide.",
      },
    ],
    fields: [
      {
        id: "workstreams",
        label: "Workstreams",
        type: "step",
        description: "Four workstreams or tracks that need timing and sequence.",
        required: true,
      },
    ],
    order: 60,
    featured: true,
  },
  {
    id: "core.phases",
    kind: "phases",
    label: "Phases",
    category: "logic",
    scope: "core",
    status: "stable",
    family: "primitive",
    semanticRole: "Grouped summary block for phased takeaways or recommendations.",
    description: "Phased summaries, grouped takeaways, and staged recommendations.",
    promptHint: "Use when the page needs grouped conclusions rather than one continuous flow.",
    useCases: [
      "Break a plan into stage-specific takeaways",
      "Group recommendations into distinct phases or themes",
    ],
    searchTerms: ["phase", "stages", "cards", "summary", "grouped takeaways"],
    rendererCapabilities: ["phase-summary"],
    skillBindings: [],
    defaultSkillRequirements: [
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Helps grouped takeaways stay concise and headline-driven.",
        role: "output",
        defaultEnabled: false,
        order: 10,
        label: "Consulting Deck",
        description: "Shape phase summaries into slide-ready grouped conclusions.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["domain", "output"],
    incompatibleSkillIds: [],
    examples: [
      {
        id: "phases.grouped-recommendations",
        label: "Grouped recommendations",
        description: "Break recommendations into distinct stages or themes.",
      },
    ],
    fields: [
      {
        id: "phase-groups",
        label: "Phase groups",
        type: "phase",
        description: "Four grouped takeaways, themes, or stages.",
        required: true,
      },
    ],
    order: 70,
    featured: true,
  },
  {
    id: "framework.swot.matrix",
    kind: "matrix",
    label: "SWOT",
    category: "comparison",
    scope: "community",
    status: "beta",
    family: "framework",
    semanticRole: "Four-quadrant strategic diagnostic that separates internal and external factors.",
    description: "A strategic SWOT template using the matrix renderer as a framework, not just a generic grid.",
    promptHint: "Use when the page should diagnose strengths, weaknesses, opportunities, and threats as a coherent strategy frame.",
    useCases: [
      "Turn a situation analysis into a structured SWOT readout",
      "Explain internal capabilities versus external risks in one page",
    ],
    searchTerms: ["swot", "strengths", "weaknesses", "opportunities", "threats", "framework"],
    rendererCapabilities: ["matrix-grid"],
    skillBindings: [
      {
        id: "builtin.framework.swot",
        label: "SWOT framing",
        status: "recommended",
        source: "builtin",
        description: "Treat the four cards as strengths, weaknesses, opportunities, and threats rather than generic buckets.",
      },
    ],
    defaultSkillRequirements: [
      {
        skillId: "skill.framework.swot",
        status: "required",
        reason: "The module only works correctly when the AI reasons as a true SWOT.",
        role: "framework",
        defaultEnabled: true,
        order: 1,
        label: "SWOT",
        description: "Separate internal and external factors correctly.",
        source: "skill",
      },
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Improves slide readability and concise structured output.",
        role: "output",
        defaultEnabled: true,
        order: 20,
        label: "Consulting Deck",
        description: "Keep quadrants short and decision-oriented.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["framework", "domain", "output"],
    incompatibleSkillIds: [],
    examples: STRATEGY_MODULE_EXAMPLES,
    fields: [
      {
        id: "strengths",
        label: "Strengths",
        type: "dimension",
        description: "Internal strengths that support the thesis.",
        required: true,
      },
      {
        id: "weaknesses",
        label: "Weaknesses",
        type: "dimension",
        description: "Internal weaknesses that limit the thesis.",
        required: true,
      },
      {
        id: "opportunities",
        label: "Opportunities",
        type: "dimension",
        description: "External openings the page should surface.",
        required: true,
      },
      {
        id: "threats",
        label: "Threats",
        type: "dimension",
        description: "External risks or threats that change the decision.",
        required: true,
      },
    ],
    order: 210,
    featured: true,
  },
  {
    id: "framework.porter-five-forces.matrix",
    kind: "matrix",
    label: "Porter Five Forces",
    category: "comparison",
    scope: "community",
    status: "beta",
    family: "framework",
    semanticRole: "Industry-structure framework that maps force intensity and strategic pressure.",
    description: "A five-forces strategy template that uses the matrix family to express competitive pressure, not a generic comparison grid.",
    promptHint: "Use when the page should explain industry attractiveness or pressure through Porter’s Five Forces.",
    useCases: [
      "Summarize bargaining power, substitutes, rivalry, entrants, and suppliers in one view",
      "Translate sector structure into strategic pressure points",
    ],
    searchTerms: ["porter", "five forces", "industry structure", "competition", "substitutes"],
    rendererCapabilities: ["matrix-grid"],
    skillBindings: [
      {
        id: "builtin.framework.porter-five-forces",
        label: "Five-forces framing",
        status: "recommended",
        source: "builtin",
        description: "Keep the analysis anchored in entrants, suppliers, buyers, substitutes, and rivalry instead of generic pros and cons.",
      },
    ],
    defaultSkillRequirements: [
      {
        skillId: "skill.framework.porter-five-forces",
        status: "required",
        reason: "The module should reason through Porter, not generic comparison logic.",
        role: "framework",
        defaultEnabled: true,
        order: 1,
        label: "Porter Five Forces",
        description: "Anchor the analysis in the five competitive forces.",
        source: "skill",
      },
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Improves structure and concise strategic language.",
        role: "output",
        defaultEnabled: true,
        order: 20,
        label: "Consulting Deck",
        description: "Keep force analysis crisp and slide-readable.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["framework", "domain", "output"],
    incompatibleSkillIds: [],
    examples: STRATEGY_MODULE_EXAMPLES,
    fields: [
      {
        id: "force-intensity",
        label: "Force intensity",
        type: "comparison-axis",
        description: "How strong each force is in the market.",
        required: false,
      },
      {
        id: "strategic-pressure",
        label: "Strategic pressure",
        type: "comparison-axis",
        description: "How that force changes strategic attractiveness or margin pressure.",
        required: false,
      },
    ],
    order: 220,
    featured: true,
  },
  {
    id: "framework.growth-curve.line",
    kind: "line",
    label: "Growth Curve",
    category: "evidence",
    scope: "community",
    status: "beta",
    family: "framework",
    semanticRole: "Lifecycle or adoption curve template that explains movement across stages.",
    description: "A growth-curve template that uses the line renderer to tell a staged growth or adoption story.",
    promptHint: "Use when the page should show a curve, lifecycle, or S-curve rather than a generic trend line.",
    useCases: [
      "Explain how adoption moves from early traction to scale",
      "Map a business or technology onto a growth-stage curve",
    ],
    searchTerms: ["growth curve", "s-curve", "adoption curve", "lifecycle", "trajectory"],
    rendererCapabilities: ["trend-line"],
    skillBindings: [
      {
        id: "builtin.framework.growth-curve",
        label: "Growth-curve framing",
        status: "recommended",
        source: "builtin",
        description: "Interpret the four points as stages on a curve with clear shifts in momentum, not just four unrelated dates.",
      },
    ],
    defaultSkillRequirements: [
      {
        skillId: "skill.framework.growth-curve",
        status: "required",
        reason: "The module needs staged-curve logic rather than generic timeline logic.",
        role: "framework",
        defaultEnabled: true,
        order: 1,
        label: "Growth Curve",
        description: "Map the line to a coherent lifecycle or adoption curve.",
        source: "skill",
      },
      {
        skillId: "skill.output.consulting-deck",
        status: "optional",
        reason: "Improves clarity of stage labels and curve progression.",
        role: "output",
        defaultEnabled: true,
        order: 20,
        label: "Consulting Deck",
        description: "Keep stages concise and executive-readable.",
        source: "skill",
      },
    ],
    supportedSkillClasses: ["framework", "domain", "output"],
    incompatibleSkillIds: [],
    examples: STRATEGY_MODULE_EXAMPLES,
    fields: [
      {
        id: "curve-stage",
        label: "Curve stage",
        type: "curve",
        description: "The lifecycle or adoption stages that should anchor the curve.",
        required: true,
      },
    ],
    order: 230,
    featured: true,
  },
];
