import type { ModuleSkillPreset } from '../types';
import { SYSTEM_CREATED_AT, SYSTEM_OWNER_ID } from './constants';

export const MODULE_SKILL_PRESETS: ModuleSkillPreset[] = [
  {
    id: "preset.swot.consulting",
    version: 1,
    label: "SWOT · Consulting",
    moduleId: "framework.swot.matrix",
    skillIds: ["skill.framework.swot", "skill.output.consulting-deck"],
    requiredSkillIds: ["skill.framework.swot"],
    optionalSkillIds: ["skill.output.consulting-deck"],
    scope: "core",
    status: "stable",
    description: "A default SWOT preset that keeps the framework logic strong and the output slide-ready.",
    useCases: ["Strategy diagnosis", "Market entry assessment", "Board discussion prep"],
    compatibilitySignature: "framework.swot.matrix|skill.framework.swot|skill.output.consulting-deck",
    testSummary: {
      totalRuns: 3,
      passRuns: 3,
      warnRuns: 0,
      failRuns: 0,
      lastRunAt: SYSTEM_CREATED_AT,
    },
    createdAt: SYSTEM_CREATED_AT,
    updatedAt: SYSTEM_CREATED_AT,
    ownerId: SYSTEM_OWNER_ID,
  },
  {
    id: "preset.swot.maritime.consulting",
    version: 1,
    label: "SWOT · Maritime",
    moduleId: "framework.swot.matrix",
    skillIds: ["skill.framework.swot", "skill.domain.maritime", "skill.output.consulting-deck"],
    requiredSkillIds: ["skill.framework.swot"],
    optionalSkillIds: ["skill.domain.maritime", "skill.output.consulting-deck"],
    scope: "core",
    status: "stable",
    description: "A maritime-adapted SWOT preset for strategy and operating-risk decks.",
    useCases: ["Port strategy", "Shipping operations review", "Maritime technology assessment"],
    compatibilitySignature: "framework.swot.matrix|skill.framework.swot|skill.domain.maritime|skill.output.consulting-deck",
    testSummary: {
      totalRuns: 3,
      passRuns: 2,
      warnRuns: 1,
      failRuns: 0,
      lastRunAt: SYSTEM_CREATED_AT,
    },
    createdAt: SYSTEM_CREATED_AT,
    updatedAt: SYSTEM_CREATED_AT,
    ownerId: SYSTEM_OWNER_ID,
  },
  {
    id: "preset.porter.consulting",
    version: 1,
    label: "Porter Five Forces · Consulting",
    moduleId: "framework.porter-five-forces.matrix",
    skillIds: ["skill.framework.porter-five-forces", "skill.output.consulting-deck"],
    requiredSkillIds: ["skill.framework.porter-five-forces"],
    optionalSkillIds: ["skill.output.consulting-deck"],
    scope: "core",
    status: "stable",
    description: "A default Porter preset for explaining industry structure on one slide.",
    useCases: ["Industry attractiveness", "Competitive pressure", "Sector strategy review"],
    compatibilitySignature: "framework.porter-five-forces.matrix|skill.framework.porter-five-forces|skill.output.consulting-deck",
    testSummary: {
      totalRuns: 3,
      passRuns: 3,
      warnRuns: 0,
      failRuns: 0,
      lastRunAt: SYSTEM_CREATED_AT,
    },
    createdAt: SYSTEM_CREATED_AT,
    updatedAt: SYSTEM_CREATED_AT,
    ownerId: SYSTEM_OWNER_ID,
  },
  {
    id: "preset.growth-curve.consulting",
    version: 1,
    label: "Growth Curve · Consulting",
    moduleId: "framework.growth-curve.line",
    skillIds: ["skill.framework.growth-curve", "skill.output.consulting-deck"],
    requiredSkillIds: ["skill.framework.growth-curve"],
    optionalSkillIds: ["skill.output.consulting-deck"],
    scope: "core",
    status: "stable",
    description: "A staged curve preset for adoption, maturity, or lifecycle slides.",
    useCases: ["Adoption curve", "Maturity path", "Lifecycle narrative"],
    compatibilitySignature: "framework.growth-curve.line|skill.framework.growth-curve|skill.output.consulting-deck",
    testSummary: {
      totalRuns: 3,
      passRuns: 3,
      warnRuns: 0,
      failRuns: 0,
      lastRunAt: SYSTEM_CREATED_AT,
    },
    createdAt: SYSTEM_CREATED_AT,
    updatedAt: SYSTEM_CREATED_AT,
    ownerId: SYSTEM_OWNER_ID,
  },
];
